import Head from 'next/head';
import NavBar from '../components/navBar';
import Main from '../components/main';
import Aboutus from '../components/aboutus';
import Skills from '../components/skills';
import Projects from '../components/projects';
import ContactArea from '../components/contact';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Main />
      <Aboutus />
      <Skills />
      <Projects />
      <ContactArea />
    </>
  )
}
